#!/bin/sh
loc=$1
c=~/.config

# home folder dotfiles
cp -f ~/.bashrc ~/.bash_profile ~/.imwheelrc ~/.vimrc ~/.xprofile ~/.Xresources $loc

# .config folder dotfiles
mkdir -p $loc/.config
cp -rf $c/alacritty $c/betterlockscreenrc $c/dunst $c/fontconfig $c/i3 $c/i3blocks $c/mimeapps.list $c/mpd $c/ncmpcpp $c/nnn $c/nvim $c/picom.conf $c/sxiv $c/zathura $loc/.config

# scripts folder
cp -rf ~/myfiles/scripts $loc
