#!/bin/sh

function relative() {
    local last_unix="$(date --date="$1" +%s)"    # convert date to unix timestamp
    local now_unix="$(date +'%s')"

    local delta=$(( $now_unix - $last_unix ))

    if (( $delta < 60 ))
    then
        echo " "$delta" seconds ago"
        return
    elif ((delta < 2700))  # 45 * 60
    then
        echo " "$(( $delta / 60 ))" minutes ago";
    fi
}

UPPATH=/home/$USER/.local/share/covid.update
LAST_RUN="$(cat $UPPATH)"
case $BLOCK_BUTTON in
	1) brave "https://www.covid19india.org" > /dev/null ;;
	2) get_data ;;
	3) notify-send "last updated" "$(relative "$LAST_RUN")"
esac


get_data() {
	# extract today's and yesterday's infection count value and store in variables
	{ read last; read current; } <<< $(curl -s https://api.covid19india.org/csv/latest/case_time_series.csv | awk -F',' '{print $3}' | tail -n2)

	# set emoji and value according to increase/decrease
	if [[ $current -gt $last ]]
	then
		sign='⬆️'
		value=$(expr $current - $last)
	else
		sign='⬇️'
		value=$(expr $last - $current)
	fi
	echo "🦠:$(numfmt --to=si $current) $sign:$(numfmt --to=si $value)"
	echo "$(date +'%Y-%m-%d %H:%M:%S')" > $UPPATH
}

get_data
