#!/bin/sh
# DIR=$(fd . -H -t d ~ 2> /dev/null | dmenu -F -i -l 20) # using dmenu - deprecated
DIR=$(fd . -H -t d ~ 2> /dev/null | rofi -dmenu -i -p "pcmanfm" -sort -matching 'fuzzy' -sorting-method 'fzf')
[ -z "$DIR" ] || pcmanfm "$DIR"
