#!/bin/sh

# this script can be used to generate a menu for nativefier apps
# i have started using ferdi because it is much convenient and i have to keep on wrestling with chrome version fixes for whatsapp, the name of this script is now not suitable as it no longer launches any electron apps but rather a multitude of different programs so in the future, i 'm going to rename it to app-menu

choice=$(printf "ferdi\ndiscord\ndeemix\nkdenlive\nESPlorer\nlofi\nrofi-beats\nrun_vm\nokular-open\nrelaunch-ddterm" | dmenu -sb '#eeeded' -sf '#222831' -i -p "Choice: ")

case "$choice" in
	# whatsapp) ~/myfiles/nativefier-apps/whatsapp-linux-x64/whatsapp;;
	# notion) ~/myfiles/nativefier-apps/notion-linux-x64/notion;;
    ferdi) /usr/bin/ferdi ;;
    discord) /usr/bin/discord ;;
	deemix) ~/myfiles/music/deezer/deemix.appimage ;;
	kdenlive) ~/myfiles/appimages/kdenlive.appimage ;;
    ESPlorer) java -jar ~/drive/embedded/ESPlorer/ESPlorer.jar ;;
	lofi) ~/myfiles/scripts/lofi ;;
	rofi-beats) ~/myfiles/scripts/rofi-beats-linux ;;
	run_vm) ~/myfiles/scripts/run_vm ;;
    okular-open) ~/myfiles/scripts/okular-open ;;
    relaunch-ddterm) urxvt --title dropdown-f -e tmux;;
esac
