#!/bin/sh

# this script can be used to generate a menu for nativefier apps

choice=$(printf "whatsapp\nnotion\ndeemix\nlofi\nrelaunch-ddterm" | dmenu -sb '#eeeded' -sf '#222831' -i -p "Choice: ")
case "$choice" in
	whatsapp) ~/myfiles/nativefier-apps/whatsapp-linux-x64/whatsapp;;
	notion) ~/myfiles/nativefier-apps/notion-linux-x64/notion;;
	deemix) ~/myfiles/music/deezer/deemix/linux-x86-deezloader.net/deemix-pyweb ;;
	lofi) ~/myfiles/scripts/lofi ;;
    relaunch-ddterm) urxvt --title dropdown-f -e tmux
esac
