#!/bin/sh
soyua="Mozilla/5.0 (Linux; Android 4.0.4; Galaxy Nexus Build/IMM76B)
AppleWebKit/535.19 (KHTML, like Gecko)
Chrome/18.0.1025.133 Mobile Safari/535.19"

case $1 in
	*"scihub"*)
		wget https://sci-hub.se/$1 -qO - | grep -Eom1 'https://[^ ]+\.pdf' | wget -i - ;;
	*"arxiv"*)
		correctlink="$(echo $1 | sed 's/abs/pdf/g' )"
		wget --user-agent='lol' $correctlink ;;
	*)
		wget --user-agent=$soyua "$1" ;;
esac

echo "Done!"
