#!/bin/bash
# original script created by @Parveshdhull

# open the first file in the directory if argument is not set
FIRST=`ls -1 | head -n1`
FILE=${1:-$FIRST}
NAME=`echo "$FILE" | rev | cut -d "/" -f 1 | rev`

# Checking if file is provided with just name or full path
LOC=`dirname "$FILE"`
if [[ $LOC = *"/home/"* ]]; then
	cd "$LOC"
fi

n=0
ls | while read p; do
	n=$((n+1))
	if [[ "$p" = "$NAME" ]]; then
		ls | sxiv -bfin $n &> /dev/null
		break
	fi
done
