#!/bin/sh

# this script uses rofi's dmenu mode to launch qutebrowser with search keywords

searchstr=$(echo -e "wk\nggl\nwd\nud\nod" | rofi -dmenu -i -p "qutebrowser-search")

[ -z "$searchstr" ] || qutebrowser ":open $searchstr" &> /dev/null




