#!/bin/sh

# read the entries in ./lists/rclone-remotes as associative array
# separated by :
declare -A remotes
while read -r line; do
    IFS=':' read -r -a array <<< "$line"
    remotes[${array[0]}]=${array[1]}
done < lists/rclone-remotes

# loop through the associative array and check if any of the keys
# appear when grepping in /proc/mounts
# store appearing key in a list
declare -a mounted
for key in "${!remotes[@]}"; do
    if grep -q "${remotes[$key]}" /proc/mounts; then
        mounted+=("$key")
    fi
done

# show a dmenu prompt to select a remote to unmount
selected=$(echo "${mounted[@]}" | dmenu -i -p "Unmount")

# if selected is not empty
if [ -n "$selected" ]; then
    fusermount -u "${remotes[$selected]}"

    # check if the selected remote is still mounted
    # if not mount, notify that it was unmounted
    # else notify that it was not unmounted
    if ! grep -q "${remotes[$selected]}" /proc/mounts; then
        notify-send "rclone-mount" "Unmounted ${remotes[$selected]}"
    else
        notify-send "rclone-mount" "Could not unmount ${remotes[$selected]}"
    fi
fi