#!/bin/sh
# useful for toggling programs that don't bind to the shell
# after executing them

if [ -z $1 ]; then
    echo "ERROR: no arg provided!"
fi

PROG="$1"

if pgrep $PROG > /dev/null
then
	echo -e "$PROG is running!\nnow terminating.."
	pkill $PROG
	notify-send -t 2000 "toggleq" "$PROG terminated"
else
	echo -e "$PROG is not running!\nnow launching $PROG"
	setsid $PROG & > /dev/null
	notify-send -t 2000 "toggleq" "$PROG launched"
fi
